feat: Add dynamic compilation of postgres hash to support any version
sandord/Respawn.Postgres pull request #4
Opened 2019-09-20 03:50 UTC by sandcastle

@sandord as discussed in #1, this PR will dynamically pull all of the columns based on the following query. 

I have tested on `9.6` so far; I think more testing is required before this should be considered ready to merge. Ideally, the test suite is expanded to automatically test against all currently supported versions Postgres via alpine containers.

```sql
select 
	t.table_name as view_name,
	c.column_name
from information_schema.tables t
left join information_schema.columns c 
	on t.table_schema = c.table_schema 
	and t.table_name = c.table_name
where (table_type = 'VIEW' and t.table_name = 'columns')
or t.table_type = 'BASE TABLE' and t.table_name in (
	'pg_class',
	'pg_type',
	'pg_attrdef',
	'pg_namespace',
	'pg_constraint'
)
;
```

2019-09-24 11:48 UTC, sandord requested changes

2019-09-24 11:48 UTC, sandord commented on src/Respawn.Postgres/PostgresHelper.cs
> +            Debug.Assert(columns.Count == 136, "Not all columns were read!");
I guess this assertion should be removed since different versions of Postgres will yield different column counts.

2019-09-24 12:40 UTC, sandcastle commented on src/Respawn.Postgres/PostgresHelper.cs
> +            Debug.Assert(columns.Count == 136, "Not all columns were read!");
@sandord - lol, that assert was for my testing only, I will remove this line

2019-09-25 00:00 UTC, sandcastle commented
@sandord looks like the build is failing because of how the build script is creating the assembly versions

2019-09-25 08:06 UTC, sandord commented
> @sandord looks like the build is failing because of how the build script is creating the assembly versions

The AppVeyor logs show that the usual version suffix is now prefixed with something like `ci-00015`. So the final suffix becomes `ci-00015-9e7c1ae`. It might be too long as apposed to the usual `-9e7c1ae`. Or the omission of the leading dash may be a problem.

Perhaps it happens due to the fact that the build is not on the default master branch. We'll see what happens when I merge the PR.

2019-09-25 08:54 UTC, sandcastle commented
> It might be too long as apposed to the usual -9e7c1ae. Or the omission of the leading dash may be a problem.

.Net only allows `int` for `major`.`minor`.`build`.`revision`

2019-09-25 09:02 UTC, sandord commented
> > It might be too long as apposed to the usual -9e7c1ae. Or the omission of the leading dash may be a problem.
> 
> .Net only allows `int` for `major`.`minor`.`build`.`revision`

As it seems, the suffix isn't applied to the .NET version. I've disabled PR builds on AppVeyor. I'm assuming that master builds will still work like before.

2019-09-25 09:22 UTC, sandord commented
Test succeeds with Postgres 11.5.

2019-10-02 02:51 UTC, sandcastle commented
@sandord - What else do we need to do to merge this?

2019-10-04 13:06 UTC, sandord commented
> @sandord - What else do we need to do to merge this?

I think we should test some more Postgres versions and perhaps improve the integration test to verify that the respawning actually works. Currently, the test only verifies that no error occurs.

2019-10-30 14:13 UTC, sandord commented
My apologies, I'm very busy these days so I really can't find time to test it now. I'm inclined to merge this PR, if you find it's working fine for you. Do you agree?

2020-04-27 11:48 UTC, sandord commented
Again, my apologies for not responding for a long time. 

In the meantime however, I have updated `master` to test against multiple versions of Postgres, namely:

- 12.2
- 11.7
- 10.12
- 9.6.17
- 9.5.21

These are the latest versions of each major version that is available on Docker Hub.

I ran your PR against the updated tests and they all pass! So as far as I'm concerned, we can merge this PR.

2020-04-30 06:33 UTC, merged